# Export some variable found by CMake


PARFLOW_VERSION_STRING="v3.13.0"
PARFLOW_VERSION="3.13.0"
PARFLOW_VERSION_MAJOR=3
PARFLOW_VERSION_MINOR=13
PARFLOW_VERSION_PATCH=0
PARFLOW_VERSION_HASH=""
PARFLOW_VERSION_EXTRA=""

MPIEXEC="/usr/bin/mpiexec"
MPIEXEC_NUMPROC_FLAG="-n"
MPIEXEC_POSTFLAGS=""
MPIEXEC_PREFLAGS=""
