# CMake generated Testfile for 
# Source directory: /workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc
# Build directory: /workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/build_deb/test/tcl/clm/pfclm_sc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pfclm_sc.tcl "/usr/bin/cmake" "-DPARFLOW_TEST=pfclm_sc.tcl;1;1;1" "-DPARFLOW_HAVE_OAS3=" "-DPARFLOW_HAVE_SILO=yes" "-DTCL_TCLSH=/bin/tclsh" "-P" "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/RunParallelTest.cmake")
set_tests_properties(pfclm_sc.tcl PROPERTIES  TIMEOUT "3600" WORKING_DIRECTORY "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc" _BACKTRACE_TRIPLES "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/ParflowTest.cmake;45;add_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;21;pf_add_sequential_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;0;")
add_test(pfclm_sc.tcl_1_2_1 "/usr/bin/cmake" "-DPARFLOW_TEST=pfclm_sc.tcl;1;2;1" "-DMPIEXEC=/usr/bin/mpiexec" "-DMPIEXEC_NUMPROC_FLAG=-n" "-DMPIEXEC_PREFLAGS=" "-DMPIEXEC_POSTFLAGS=" "-DPARFLOW_HAVE_OAS3={PARFLOW_HAVE_OAS3}" "-DPARFLOW_HAVE_SILO=yes" "-DTCL_TCLSH=/bin/tclsh" "-P" "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/RunParallelTest.cmake")
set_tests_properties(pfclm_sc.tcl_1_2_1 PROPERTIES  TIMEOUT "3600" WORKING_DIRECTORY "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc" _BACKTRACE_TRIPLES "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/ParflowTest.cmake;25;add_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;26;pf_add_parallel_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;0;")
add_test(pfclm_sc.tcl_2_1_1 "/usr/bin/cmake" "-DPARFLOW_TEST=pfclm_sc.tcl;2;1;1" "-DMPIEXEC=/usr/bin/mpiexec" "-DMPIEXEC_NUMPROC_FLAG=-n" "-DMPIEXEC_PREFLAGS=" "-DMPIEXEC_POSTFLAGS=" "-DPARFLOW_HAVE_OAS3={PARFLOW_HAVE_OAS3}" "-DPARFLOW_HAVE_SILO=yes" "-DTCL_TCLSH=/bin/tclsh" "-P" "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/RunParallelTest.cmake")
set_tests_properties(pfclm_sc.tcl_2_1_1 PROPERTIES  TIMEOUT "3600" WORKING_DIRECTORY "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc" _BACKTRACE_TRIPLES "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/ParflowTest.cmake;25;add_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;26;pf_add_parallel_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;0;")
add_test(pfclm_sc.tcl_2_2_1 "/usr/bin/cmake" "-DPARFLOW_TEST=pfclm_sc.tcl;2;2;1" "-DMPIEXEC=/usr/bin/mpiexec" "-DMPIEXEC_NUMPROC_FLAG=-n" "-DMPIEXEC_PREFLAGS=" "-DMPIEXEC_POSTFLAGS=" "-DPARFLOW_HAVE_OAS3={PARFLOW_HAVE_OAS3}" "-DPARFLOW_HAVE_SILO=yes" "-DTCL_TCLSH=/bin/tclsh" "-P" "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/RunParallelTest.cmake")
set_tests_properties(pfclm_sc.tcl_2_2_1 PROPERTIES  TIMEOUT "3600" WORKING_DIRECTORY "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc" _BACKTRACE_TRIPLES "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/ParflowTest.cmake;25;add_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;26;pf_add_parallel_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;0;")
add_test(pfclm_sc.tcl_3_3_1 "/usr/bin/cmake" "-DPARFLOW_TEST=pfclm_sc.tcl;3;3;1" "-DMPIEXEC=/usr/bin/mpiexec" "-DMPIEXEC_NUMPROC_FLAG=-n" "-DMPIEXEC_PREFLAGS=" "-DMPIEXEC_POSTFLAGS=" "-DPARFLOW_HAVE_OAS3={PARFLOW_HAVE_OAS3}" "-DPARFLOW_HAVE_SILO=yes" "-DTCL_TCLSH=/bin/tclsh" "-P" "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/RunParallelTest.cmake")
set_tests_properties(pfclm_sc.tcl_3_3_1 PROPERTIES  TIMEOUT "3600" WORKING_DIRECTORY "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc" _BACKTRACE_TRIPLES "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/ParflowTest.cmake;25;add_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;26;pf_add_parallel_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;0;")
add_test(pfclm_sc.tcl_1_4_1 "/usr/bin/cmake" "-DPARFLOW_TEST=pfclm_sc.tcl;1;4;1" "-DMPIEXEC=/usr/bin/mpiexec" "-DMPIEXEC_NUMPROC_FLAG=-n" "-DMPIEXEC_PREFLAGS=" "-DMPIEXEC_POSTFLAGS=" "-DPARFLOW_HAVE_OAS3={PARFLOW_HAVE_OAS3}" "-DPARFLOW_HAVE_SILO=yes" "-DTCL_TCLSH=/bin/tclsh" "-P" "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/RunParallelTest.cmake")
set_tests_properties(pfclm_sc.tcl_1_4_1 PROPERTIES  TIMEOUT "3600" WORKING_DIRECTORY "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc" _BACKTRACE_TRIPLES "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/ParflowTest.cmake;25;add_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;26;pf_add_parallel_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;0;")
add_test(pfclm_sc.tcl_4_1_1 "/usr/bin/cmake" "-DPARFLOW_TEST=pfclm_sc.tcl;4;1;1" "-DMPIEXEC=/usr/bin/mpiexec" "-DMPIEXEC_NUMPROC_FLAG=-n" "-DMPIEXEC_PREFLAGS=" "-DMPIEXEC_POSTFLAGS=" "-DPARFLOW_HAVE_OAS3={PARFLOW_HAVE_OAS3}" "-DPARFLOW_HAVE_SILO=yes" "-DTCL_TCLSH=/bin/tclsh" "-P" "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/RunParallelTest.cmake")
set_tests_properties(pfclm_sc.tcl_4_1_1 PROPERTIES  TIMEOUT "3600" WORKING_DIRECTORY "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc" _BACKTRACE_TRIPLES "/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/cmake/modules/ParflowTest.cmake;25;add_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;26;pf_add_parallel_test;/workdir2/phyrev/reverdya/parflow/parflow_src/snow_params/test/tcl/clm/pfclm_sc/CMakeLists.txt;0;")
